apiVersion: v1
kind: Service
metadata:
  name: {{ include "papergraph.name" . }}-api
  labels:
    {{- include "papergraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.serviceType }}
  {{- if .Values.api.loadBalancerIP }}
  loadBalancerIP: {{ .Values.api.loadBalancerIP | quote }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "papergraph.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
