{{- if .Values.cloudRunUi.enabled }}
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: {{ .Values.cloudRunUi.serviceName }}
  labels:
    {{- include "papergraph.labels" . | nindent 4 }}
spec:
  location: {{ .Values.cloudRunUi.location }}
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccount.gcpServiceAccount | quote }}
      containers:
        - image: {{ .Values.images.ui | quote }}
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: {{ .Values.external.apiUrl | quote }}
{{- end }}
