{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
  labels:
    {{- include "papergraph.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.projectId | quote }}
{{- end }}
