{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "papergraph.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.gcpServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount | quote }}
  {{- end }}
{{- end }}
